export const GET_WOLRD_POPULATION = 'world/GET_WOLRD_POPULATION'
export const GET_ALL_COUNTRY = 'world/GET_ALL_COUNTRY'
export const GET_COUNTRY_POPULATION = 'world/GET_COUNTRY_POPULATION'
export const GET_TOP_COUNTRY_POPULATION = 'world/GET_TOP_COUNTRY_POPULATION'


